# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36

install: pip install tox

script: tox

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
