name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check package
      run: |
        python -m pip install --upgrade pip
        pip install check-manifest flake8
        check-manifest
        flake8 .
    - name: Install dependencies
      run: |
        python -c "import configparser; c=configparser.ConfigParser(); c.read('setup.cfg'); print(c['options']['install_requires'])" > requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run package creation
      run: |
        python -m pip install --user --upgrade build
        python -m build
    - name: Run Unit Tests and generate coverage report
      run: |
        pip install coverage
        coverage run -m unittest discover
        coverage report -m
        coverage xml
        coverage html
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        verbose: false
    - name: Archive code coverage html report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: htmlcov
    #- name: Archive package
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: imagedata
    #    path: src/dist    
